lib/discuss_web/router.ex
defmodule DiscussWeb.Router do
  use DiscussWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug DiscussWeb.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", DiscussWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  scope "/topics", DiscussWeb do
    pipe_through :browser

    resources "/", TopicController, only: [:index, :new, :create, :edit, :update, :delete]
  end

  scope "/auth", DiscussWeb do
    pipe_through :browser

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
    get "/logout", AuthController, :delete
    delete "/logout", AuthController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", DiscussWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: DiscussWeb.Telemetry
    end
  end
end

lib/discuss/application.ex
defmodule Discuss.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      Discuss.Repo,
      # Start the Telemetry supervisor
      DiscussWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: Discuss.PubSub},
      # Start the Endpoint (http/https)
      DiscussWeb.Endpoint
      # Start a worker by calling: Discuss.Worker.start_link(arg)
      # {Discuss.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Discuss.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    DiscussWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/discuss/authentication.ex
defmodule Discuss.Authentication do
  @moduledoc """
  The Discussion context.
  """

  import Ecto.Query, warn: false
  alias Discuss.Repo

  alias Discuss.Authentication.User

  def get_user(id) do
    Repo.get(User, id)
  end

  def find_or_create_user(attrs \\ %{}) do
    changeset = User.changeset(%User{}, attrs)

    %{ changes: %{ email: email } } = changeset

    case Repo.get_by(User, email: email) do
      nil ->
        Repo.insert(changeset)
      user ->
        user
        |> User.changeset(attrs)
        |> Repo.update()
    end
  end
end

lib/discuss/authentication/user.ex
defmodule Discuss.Authentication.User do
  use Ecto.Schema
  import Ecto.Changeset

  schema "users" do
    field :email, :string
    field :provider, :string
    field :token, :string

    has_many :topics, Discuss.Discussion.Topic
  end

  def changeset(user, attrs \\ %{}) do
    user
    |> cast(attrs, [:email, :provider, :token])
    |> validate_required([:email, :provider, :token])
  end
end

lib/discuss/discussion.ex
defmodule Discuss.Discussion do
  @moduledoc """
  The Discussion context.
  """
  import Ecto
  import Ecto.Query, warn: false
  alias Discuss.Repo

  alias Discuss.Discussion.Topic

  def change_topic(%Topic{} = topic, attrs \\ %{}) do
    Topic.changeset(topic, attrs)
  end

  def get_topic!(id), do: Repo.get!(Topic, id)

  def list_topics do
    Repo.all(Topic)
  end

  def create_topic(user, attrs \\ %{}) do
    user
    |> build_assoc(:topics)
    |> Topic.changeset(attrs)
    |> Repo.insert()
  end

  def update_topic(%Topic{} = topic, attrs \\ %{}) do
    topic
    |> Topic.changeset(attrs)
    |> Repo.update()
  end

  def delete_topic(topic) do
    Repo.delete!(topic)
  end
end

lib/discuss/discussion/topic.ex
defmodule Discuss.Discussion.Topic do
  use Ecto.Schema
  import Ecto.Changeset

  schema "topics" do
    field :title, :string

    belongs_to :user, Discuss.Authentication.User
  end

  def changeset(topic, attrs \\ %{}) do
    topic
    |> cast(attrs, [:title])
    |> cast_assoc(:user)
    |> validate_required([:title])
    |> assoc_constraint(:user)
  end
end

lib/discuss/repo.ex
defmodule Discuss.Repo do
  use Ecto.Repo,
    otp_app: :discuss,
    adapter: Ecto.Adapters.Postgres
end

lib/discuss_web/controllers/page_controller.ex
defmodule DiscussWeb.PageController do
  use DiscussWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/discuss_web/controllers/topic_controller.ex
defmodule DiscussWeb.TopicController do
  use DiscussWeb, :controller

  alias Discuss.Discussion
  alias Discuss.Discussion.Topic

  plug DiscussWeb.Plugs.RequireAuth when action in [:new, :create, :edit, :update, :delete]
  plug :require_ownership when action in [:update, :edit, :delete]

  def require_ownership(conn, _params) do
    %{params: %{"id" => topic_id}} = conn
    %{id: user_id} = conn.assigns[:user]

    if topic_id == user_id do
      conn
    else
      conn
      |> put_flash(:error, "Access denied, only the owner of this topic can access this operation.")
      |> redirect(to: Routes.page_path(conn, :index))
      |> halt()
    end
  end

  def index(conn, _params) do
    IO.inspect(conn.assigns[:user])
    topics = Discussion.list_topics()

    render(conn, "index.html", topics: topics)
  end

  def new(conn, _params) do
    changeset = Discussion.change_topic(%Topic{})

    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"topic" => topic_params}) do
    case Discussion.create_topic(conn.assigns[:user], topic_params) do

      {:ok, _topic} ->

        conn
        |> put_flash(:info, "Topic created successfully.")
        |> redirect(to: Routes.topic_path(conn, :index))

      {:error, changeset} ->

        case changeset.errors[:user] do

          nil ->

            conn
            |> put_flash(:error, "Error, check the errors below.")
            |> render("new.html", changeset: changeset)

          _ ->

            conn
            |> put_flash(:error, "Something went wrong, please sign in again")
            |> clear_session()
            |> redirect(to: Routes.page_path(conn, :index))

        end

    end
  end

  def edit(conn, %{"id" => topic_id}) do
    topic = Discussion.get_topic!(topic_id)
    changeset = Discussion.change_topic(topic)

    render(conn, "edit.html", topic: topic, changeset: changeset)
  end

  def update(conn, %{"id" => topic_id, "topic" => topic_params}) do
    topic = Discussion.get_topic!(topic_id)

    case Discussion.update_topic(topic, topic_params) do
      {:ok, _topic} ->
        conn
        |> put_flash(:info, "Topic updated successfully.")
        |> redirect(to: Routes.topic_path(conn, :index))

      {:error, changeset} ->
        conn
        |> put_flash(:error, "Error, check the errors below.")
        |> render("edit.html", topic: topic, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => topic_id}) do
    topic = Discussion.get_topic!(topic_id)

    Discussion.delete_topic(topic)

    conn
    |> put_flash(:info, "Topic deleted successfully.")
    |> redirect(to: Routes.topic_path(conn, :index))
  end
end

lib/discuss_web/views/error_view.ex
defmodule DiscussWeb.ErrorView do
  use DiscussWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/discuss_web/views/layout_view.ex
defmodule DiscussWeb.LayoutView do
  use DiscussWeb, :view
end

lib/discuss_web/views/page_view.ex
defmodule DiscussWeb.PageView do
  use DiscussWeb, :view
end

lib/discuss_web/views/topic_view.ex
defmodule DiscussWeb.TopicView do
  use DiscussWeb, :view
end

lib/discuss_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Discuss · Phoenix Framework</title>

    <!-- CSS -->
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- JS -->
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/materialize.js") %>"></script>

  </head>

  <body>

    <header>

      <nav class="light-blue">
        <div class="nav-wrapper container">

          <%= link to: Routes.page_path(@conn, :index), class: "brand-logo center" do %> Discussions <% end %>
          <a href="" data-target="mobile-demo" class="sidenav-trigger show-on-large"><i class="material-icons">menu</i></a>

          <ul id="nav-mobile" class="right">

            <%= if @conn.assigns[:user] do %>
              <li> <%= link to: Routes.auth_path(@conn, :delete), method: :delete do %> Sing Out <% end %> </li>
            <% else %>
              <li> <%= link to: Routes.auth_path(@conn, :request, :github) do %> Sign In with Github <% end %> </li>
            <% end %>

          </ul>

        </div>
      </nav>

      <ul class="sidenav" id="mobile-demo">

        <li> <%= link to: Routes.topic_path(@conn, :index) do %> List of Topics <% end %> </li>
        <li> <%= link to: Routes.topic_path(@conn, :new) do %> Add Topic <% end %> </li>

      </ul>

    </header>

    <main role="main" class="container">

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <%= @inner_content %>

    </main>

  </body>

</html>

lib/discuss_web/templates/page/index.html.eex
<h3 class="center"> My Awesome Landing Page </h3>

<div class="center">

  <%= link to: Routes.topic_path(@conn, :index) do %>

    <button class="waves-effect waves-light btn"> Join The Discussion </button>

  <% end %>

</div

lib/discuss_web/templates/topic/edit.html.eex
<%= form_for @changeset, Routes.topic_path(@conn, :update, @topic), fn f -> %>

  <div class="col s12">

    <div class="row">
      <h3> Edit Your Topic </h1>
    </div>

    <div class="row">
      <div class="input-field">

        <%= label f, :title, for: "title-input" %>
        <%= text_input f, :title, type: "text", id: "title-input" %>
        <%= error_tag f, :title %>

      </div>
    </div>

    <div class="row">
      <%= submit "Save Topic", class: "waves-effect waves-light btn" %>
    </div>

  </div>

<% end %>

lib/discuss_web/templates/topic/index.html.eex
<div class="col s12">

  <div class="row">
    <h3> Topics </h1>
  </div>

  <div class="row">
    <ul class="collection">

      <%= for topic <- @topics do %>

        <li>
          <div class="collection-item">

            <%= topic.title %>

            <%= if @conn.assigns.user.id == topic.user_id do %>

              <%= link to: Routes.topic_path(@conn, :delete, topic), method: :delete, class: "secondary-content", style: "padding: 5px !important;" do %>
              <i class="material-icons">delete</i>
              <% end %>

              <%= link to: Routes.topic_path(@conn, :edit, topic), class: "secondary-content", style: "padding: 5px !important;" do %>
                <i class="material-icons">edit</i>
              <% end %>

            <% end %>

          </div>
        </li>

      <% end %>

    </ul>
  </div>

  <div class="fixed-action-btn">
    <%= link to: Routes.topic_path(@conn, :new), class: "btn-floating btn-large waves-effect waves-light red" do %>

      <i class="material-icons">add</i>

    <% end %>
  </div>

</div>

lib/discuss_web/templates/topic/new.html.eex
<%= form_for @changeset, Routes.topic_path(@conn, :create), fn f -> %>

  <div class="col s12">

    <div class="row">
      <h3> Create a New Topic </h1>
    </div>

    <div class="row">
      <div class="input-field">

        <%= label f, :title, for: "title-input" %>
        <%= text_input f, :title, type: "text", id: "title-input" %>
        <%= error_tag f, :title %>

      </div>
    </div>

    <div class="row">
      <%= submit "Save Topic", class: "waves-effect waves-light btn" %>
    </div>

  </div>

<% end %>